//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Users2Courses = new List<Users2Courses>();
        }
    
        public int id { get; set; }
        public int specialization_id { get; set; }
        public string name { get; set; }
        public int study_year { get; set; }
        public byte semester { get; set; }
        public byte study_level { get; set; }
        public byte credits { get; set; }
        public int course_hours { get; set; }
        public int laboratory_hours { get; set; }
        public int seminary_hours { get; set; }
        public int project_hours { get; set; }
        public string content { get; set; }
        public string laboratory_tutors { get; set; }
        public string seminary_tutors { get; set; }
        public string project_tutors { get; set; }
    
        public virtual Specialization Specialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Users2Courses> Users2Courses { get; set; }
        public override string ToString()
        {
            return name;
        }
    }
}
